# Generated by Django 4.2.1 on 2023-06-07 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='get_professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Completo', models.CharField(max_length=250)),
                ('Nombres', models.CharField(max_length=50)),
                ('Apellidos', models.CharField(max_length=50)),
                ('Ultima_Conexion', models.CharField(max_length=100)),
                ('Dias_no_conexion', models.CharField(max_length=50)),
                ('Foto_perfil', models.CharField(max_length=10)),
                ('Presentacion_Docente', models.CharField(max_length=10)),
                ('Fecha_Informe', models.CharField(max_length=100)),
                ('Correo', models.CharField(max_length=50)),
            ],
        ),
    ]
